server:
  port: 8080

spring:
  profiles:
    include: secret
  datasource:
    url: jdbc:mysql://cowinsta.c3oss08cegbp.ap-northeast-2.rds.amazonaws.com:3306/cowinsta?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect

    show_sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: thisissecret

cloud:
  aws:
    s3:
      bucket: cowinsta
    credentials:
      access-key: 3bzY03TJTAwWJyW8K1sbBEYBhcI2W9lPfftAPlZn98s=
      secret-key: 6Gf5oEZYRDNKcefXBC/8iaTGEe6apjj9MQVBNAxh/xiW8URt0+qcg9W3oReB7VmpQRSdJkbJepY=

    region:
      static: ap-southeast-2
      auto: false
    stack:
      auto: false
jwt:
  secret:
    fsdgwr23524!dfswg43dfwfe@sgwrg!!sdgrgsdjoim!!!odvoiwslknie!!!!soivoihrgio
