server:
  port: 8080

spring:
  profiles:
    include: secret
  datasource:
    url: jdbc:mysql://localhost:3307/jpa?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

    show_sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

cloud:
  aws:
    s3:
      bucket: cowinsta
    credentials:
      access-key: ENC(hlfZvG+yIeRcaYP0TFNBe24tEmParNxrhmkkfTeLkqU=)
      secret-key: ENC(Os4hmWqWPQPrfv5kUuFyJK0FSr9R/DBkfy1jvTOp5bqQOBZLvbQo5REfxcUwnzPenT6/MHX7q0A=)
    region:
      static: ap-southeast-2
      auto: false
    stack:
      auto: false
jwt:
  secret:
    fsdgwr23524!dfswg43dfwfe@sgwrg!!sdgrgsdjoim!!!odvoiwslknie!!!!soivoihrgio
