server:
  port: 8080

spring:
  profiles:
    include: secret
  datasource:
    url: jdbc:mysql://localhost:3307/jpa?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

    show_sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: thisissecret

cloud:
  aws:
    s3:
      bucket: cowinsta
    credentials:
      access-key: 3bzY03TJTAwWJyW8K1sbBEYBhcI2W9lPfftAPlZn98s=
      secret-key: 6Gf5oEZYRDNKcefXBC/8iaTGEe6apjj9MQVBNAxh/xiW8URt0+qcg9W3oReB7VmpQRSdJkbJepY=

    region:
      static: ap-southeast-2
      auto: false
    stack:
      auto: false
jwt:
  secret:
    fsdgwr23524!dfswg43dfwfe@sgwrg!!sdgrgsdjoim!!!odvoiwslknie!!!!soivoihrgio
